# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 08:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_auto_20160221_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_news',
            name='upload',
            field=models.FileField(default=b'null', upload_to=b'static/img/usruploads/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateField(default=datetime.date(2016, 2, 22)),
        ),
    ]
