# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_auto_20160222_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_news',
            name='upload',
            field=models.FileField(default=b'null', upload_to=b'tatic/img/uploads/'),
        ),
    ]
