# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0006_auto_20160222_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_news',
            name='upload',
            field=models.FileField(default=b'null', upload_to=b'static/img/usruploads/'),
        ),
    ]
