# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0007_auto_20160222_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_n',
            name='upload',
            field=models.ImageField(upload_to=b'static/img/usruploads'),
        ),
    ]
