# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 05:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0012_auto_20160224_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_news',
            name='upload',
            field=models.FileField(default=False, upload_to=b'static/img/usruploads/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateField(default=datetime.date(2016, 2, 26)),
        ),
    ]
