# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 04:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0016_auto_20160406_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpassword',
            name='key_expires',
            field=models.DateField(default=datetime.date(2016, 4, 15)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateField(default=datetime.date(2016, 4, 15)),
        ),
    ]
