# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-01 05:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0019_auto_20160417_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpassword',
            name='key_expires',
            field=models.DateField(default=datetime.date(2016, 5, 1)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateField(default=datetime.date(2016, 5, 1)),
        ),
    ]
